name: Deploy Strapi

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_IMAGE }}:${{ github.ref_name == 'main' && 'latest' || 'develop' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  deploy:
    runs-on: self-hosted
    needs: build
    if: github.ref_name == 'main' || github.ref_name == 'develop'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync openssh-client

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      - name: Deploy to server
        env:
          DEPLOY_TARGET: ${{ secrets.DEPLOY_TARGET }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          COMPOSE_SERVICE: ${{ github.ref_name == 'main' && secrets.PROD_COMPOSE_SERVICE || secrets.DEV_COMPOSE_SERVICE }}
          COMPOSE_COMMAND: ${{ github.ref_name == 'main' && secrets.PROD_COMPOSE_COMMAND || secrets.DEV_COMPOSE_COMMAND }}
        run: |
          ssh $DEPLOY_TARGET "cd $DEPLOY_PATH && \
            $COMPOSE_COMMAND pull $COMPOSE_SERVICE && \
            $COMPOSE_COMMAND up -d $COMPOSE_SERVICE && \
            docker image prune -f"
